// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package common_proto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Helloworld
	Person
	AddressBook
*/
package common_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Helloworld struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str              *string `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	Opt              *int32  `protobuf:"varint,3,opt,name=opt" json:"opt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Helloworld) Reset()                    { *m = Helloworld{} }
func (m *Helloworld) String() string            { return proto.CompactTextString(m) }
func (*Helloworld) ProtoMessage()               {}
func (*Helloworld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Helloworld) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Helloworld) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *Helloworld) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

type Person struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string               `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone            []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*Person_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=common_proto.Person_PhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

const Default_Person_PhoneNumber_Type Person_PhoneType = Person_HOME

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Person_PhoneNumber_Type
}

type AddressBook struct {
	Person           []*Person `protobuf:"bytes,1,rep,name=person" json:"person,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressBook) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Helloworld)(nil), "common_proto.Helloworld")
	proto.RegisterType((*Person)(nil), "common_proto.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "common_proto.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "common_proto.AddressBook")
	proto.RegisterEnum("common_proto.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0x6d, 0xfa, 0x07, 0xfb, 0xba, 0x2e, 0x25, 0x78, 0x28, 0x1e, 0xa4, 0x14, 0x0f, 0x05,
	0xa1, 0x42, 0xbd, 0x79, 0x73, 0x61, 0x61, 0x45, 0xd7, 0xae, 0x22, 0x78, 0x94, 0xd5, 0x3e, 0x70,
	0xb1, 0xc9, 0x0b, 0x49, 0x44, 0xfc, 0xba, 0x7e, 0x12, 0xd3, 0xb8, 0xc8, 0x1e, 0xf4, 0xf6, 0x26,
	0xcc, 0xcc, 0x6f, 0x02, 0x60, 0xd1, 0xd8, 0x46, 0x69, 0xb2, 0xc4, 0x27, 0x2f, 0x24, 0x04, 0xc9,
	0x27, 0xaf, 0xaa, 0x16, 0x60, 0x81, 0xc3, 0x40, 0x1f, 0xa4, 0x87, 0x9e, 0x03, 0xb0, 0x4d, 0x5f,
	0x04, 0x25, 0xab, 0x63, 0x9e, 0x41, 0x68, 0xac, 0x2e, 0x98, 0x13, 0xe9, 0x28, 0x48, 0xd9, 0x22,
	0x2c, 0x83, 0x3a, 0xae, 0xbe, 0x02, 0x48, 0x56, 0xa8, 0x0d, 0x49, 0x3e, 0x81, 0x48, 0xae, 0x05,
	0xfa, 0x48, 0xba, 0x8d, 0x33, 0x1f, 0x3f, 0x80, 0x18, 0xc5, 0x7a, 0x33, 0xf8, 0x4c, 0xca, 0xcf,
	0x20, 0x56, 0xaf, 0x24, 0xb1, 0x88, 0xca, 0xb0, 0xce, 0xda, 0xb2, 0xd9, 0x5d, 0xd1, 0xfc, 0xb4,
	0x35, 0xab, 0xd1, 0x71, 0xfb, 0x2e, 0x9e, 0x51, 0x1f, 0xdd, 0x41, 0xb6, 0x23, 0xf9, 0x14, 0x12,
	0xe9, 0xaf, 0x2d, 0xaa, 0x85, 0xc8, 0x7e, 0x2a, 0x74, 0xb0, 0xa0, 0x9e, 0xb6, 0xc7, 0xff, 0xd7,
	0x3d, 0x38, 0xd7, 0x45, 0xb4, 0xe8, 0x96, 0xf3, 0xea, 0x14, 0xd2, 0xdf, 0x27, 0xb7, 0x35, 0x59,
	0x76, 0xb3, 0xab, 0x9b, 0x79, 0xbe, 0xc7, 0xf7, 0xc1, 0x1b, 0xf2, 0x60, 0xbc, 0x1e, 0xbb, 0xfb,
	0xeb, 0x9c, 0x55, 0xe7, 0x90, 0x5d, 0xf6, 0xbd, 0x46, 0x63, 0x66, 0x44, 0x6f, 0xfc, 0x04, 0x12,
	0xe5, 0x5b, 0x1d, 0x7f, 0xfc, 0xc0, 0xe1, 0x5f, 0xc4, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69,
	0xf7, 0x1d, 0x97, 0x68, 0x01, 0x00, 0x00,
}
